spring:
  cloud:
    gateway:
      routes:
        - id: ms-travels-save
          uri: lb://ms-travels-save
          predicates:
            - Path=/dev/travels/**
          filters:
            - StripPrefix=2
